version: '3.0'
services:
  doc:
    image: redocly/redoc
    ports:
      - 7777:80
    volumes:
      - ./out.yml:/usr/share/nginx/html/out.yml
    environment:
      - 'SPEC_URL=out.yml'

  mock:
    image: stoplight/prism:4
    ports:
      - 6969:4010
    volumes:
      - .:/work
    command: mock -h 0.0.0.0 /work/openapi.yml

  merger:
   build: .
   volumes:
     - .:/work
   working_dir: /work
   command: yarn -s run swagger-merger -i openapi.yml -o out.yml
   depends_on:
     - doc
