name: Lint

on:
  push:

jobs:
  lint:
    runs-on: ubuntu-latest

    steps:
    - name: checkout
      uses: actions/checkout@v3

    - name: build
      run: make build

    - name: lint
      run: make lint

  generate:
    runs-on: ubuntu-latest

    steps:
      - name: checkout
        uses: actions/checkout@v3

      - name: copy from container
        run: make gen

      - name: upload artifacts
        uses: actions/upload-artifact@v2
        with:
          path: ./html
          name: html
